### PR TITLE
fix brackets

### PR DESCRIPTION
**Pull request by mlodyskiny**

### CODE REVIEW

**Comment by mlodyskiny** [comment]
im gonna fix more later!

**Comment by kem0x** [comment]
this isn't a "fix", this style is intended we have a [clang format file](../blob/stable/.clang-format) for a reason :skull:

**Comment by mlodyskiny** [comment]
I FIX BRACKETS LET ME FIX THE FUCKING BRACKETS

**Comment by Kyiro** [comment]
> I FIX BRACKETS LET ME FIX THE FUCKING BRACKETS

I get you might prefer that type of bracket placement (I prefer it too) but not everyone wants it

**Comment by mlodyskiny** [comment]
Wake up, it's the first of the month

**Comment by samuelsiv** [comment]
wake up some bitches dude

**Comment by ramok0** [comment]
fix brackets ☠️

**Comment by mlodyskiny** [comment]
Sammy https://www.youtube.com/watch?v=gQZsXlmPQko

**Pull request closed without merging**
