### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by vinzy2**

### CODE REVIEW

**Comment by vinzy2** [comment]
might help with new users

**Comment by Milxnor** [comment]
Yes, but it doesn't look clean.

**Comment by vinzy2** [comment]
ok i get what u mean 
give me 5-10 mins

**Comment by vinzy2** [comment]
that better?

**Comment by samuelsiv** [comment]
If you were to make an useful guide maybe we can merge it but this doesn't look nowhere nice.
Closing it 👍

**Comment by Kyiro** [comment]
```
 👎😕👎
   \|/
    |
   / \
```

**Pull request closed without merging**
