### PR TITLE
Add a rejoin toggle.

### PR DESCRIPTION
**Pull request by BlurTehEpic**
Don't we all hate the idiots that rejoin and get god mode or some shit?

[A playground time unlimiter isnt mine, i kept it for my server]

### CODE REVIEW

**Comment by BlurTehEpic** [comment]
this includes Ramok's Safezone disabler for playground (and possibly his respawn fix)
https://github.com/kem0x/raider3.5/pull/82

**Comment by ramok0** [comment]
Its not implementing https://github.com/kem0x/raider3.5/pull/83 correctly, i think your server will crash when someone will disconnect. I'd recommand to just remove my code from your repo and just use your rejoin toggle function, kem0x will merge our pr later. 

thanks

**Comment by ramok0** [comment]
ready to be merged ig

**Comment by samuelsiv** [comment]
Fix the PR with a proper commit please, then remake one.

**Pull request closed without merging**
